INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Shrimp soup', 1);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Cauliflower and mushroom stew', 1);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('spicy chicken nuggets', 1);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('steamed cod fish', 1);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('turkey burger', 1);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('veggie burger', 1);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('fried egg', 1);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Chicken curry', 2);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Chicken masala', 2);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Mutton Korma', 2);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Keema Curry', 2);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Mushroom Tikka', 2);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('fried egg', 2);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('curry rice', 2);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Tofu teriyaki', 3);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Shrimp Tempura', 3);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Yaki Udon', 3);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Chicken Katsu', 3);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Salmon sashimi', 3);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('fried egg', 3);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('curry rice', 3);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Black pepper beef', 4);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Pork chowmein', 4);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Sweet & sour pork', 4);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Gongbao chicken', 4);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Pork Jiaozi', 4);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('Soy glazed pork chops', 4);
INSERT INTO `meal`(`dishes`, `chefID`) VALUES ('curry rice', 4);
